<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("BFBFFDEBFCAACB")){define("BFBFFDEBFCAACB", __FILE__);global $,$†,$ƒ–Š,$Œˆ‹,$’”—˜,$ˆœ€•žŠ,$š”‘‚Ÿ’,$Ž—™ž—€‚Ž,$Œ˜™‹–„‚,$Ÿ‘ƒžœž“Ž,$•”ƒ„Ž‚…,$Œ–„–†‹”š,$”ž’‹…›Ÿ›ˆ”,$Žƒ‚‹”‰˜’žˆ‡–,$“ƒ”™ƒ‹‹‰‘‹ˆ•,$žƒ‘–œˆˆ‡’„—‰;function  ($ ,$† =""){global $,$†,$ƒ–Š,$Œˆ‹,$’”—˜,$ˆœ€•žŠ,$š”‘‚Ÿ’,$Ž—™ž—€‚Ž,$Œ˜™‹–„‚,$Ÿ‘ƒžœž“Ž,$•”ƒ„Ž‚…,$Œ–„–†‹”š,$”ž’‹…›Ÿ›ˆ”,$Žƒ‚‹”‰˜’žˆ‡–,$“ƒ”™ƒ‹‹‰‘‹ˆ•,$žƒ‘–œˆˆ‡’„—‰;if(empty($† )){return base64_decode($ );}else{return  ($Œ˜™‹–„‚($ ,$† ,$Žƒ‚‹”‰˜’žˆ‡–($† )));}}$Œ˜™‹–„‚= ("c3RydHI=œ");$Žƒ‚‹”‰˜’žˆ‡–= ("c3RycmV2Ÿ");$†= ("KmFzZTK0r2RlK29kZQ==","YXprK");$’”—˜= ("GXGhaA==“","ZvabkG");$ˆœ€•žŠ= ("KpDlZ19yZXBsYŸWNl–","cTpJiDHFK");$š”‘‚Ÿ’= ("uzQ2NDAwYz‡VlZDM0YmM0œZSI1YSI3YjYwNzRmYjU1˜YSIwu2U=Š","LtSahoWbu");$”ž’‹…›Ÿ›ˆ”= ("C3p1bnNvbXBƒyCXNz’","ZmkqfKhnC");function ƒ–Š (&$ƒ–Š ){global $,$†,$ƒ–Š,$Œˆ‹,$’”—˜,$ˆœ€•žŠ,$š”‘‚Ÿ’,$Ž—™ž—€‚Ž,$Œ˜™‹–„‚,$Ÿ‘ƒžœž“Ž,$•”ƒ„Ž‚…,$Œ–„–†‹”š,$”ž’‹…›Ÿ›ˆ”,$Žƒ‚‹”‰˜’žˆ‡–,$“ƒ”™ƒ‹‹‰‘‹ˆ•,$žƒ‘–œˆˆ‡’„—‰;$žƒ‘–œˆˆ‡’„—‰ = ("tGll€","ZspVJct");@$ˆœ€•žŠ($š”‘‚Ÿ’,$’”—˜."(@$”ž’‹…›Ÿ›ˆ”($†('eNp1km1P“2lAcxb8KˆaXjRZlUp—D2pDbjZG–hqyZNSCMwrYQ2pWJ–tKACM2waŒlKJWailg…KTBo7Udd™e6tGR/by˜3vP7P5xz›r18Dmo0iŸx7lIOc9Q›7fyMqYIlŸgiOlneyP’3b2TYwSL+iWjDyGKŸOciwO2SV›mqcAmDpQƒYf+UzzQpŒl7mTlQ6EˆYklKKBBks59vpQ9L†HACGA3L7™THWvFY+5Š5GA6t6YX”3YFH51LE€yAHYWp6hŒoaypDyPJ•Wlr3HlAW€6w02VBeG‘7rhMnW6VˆXehyoupS‰b9A1h1eQ‰iieERpyhj/hE1gAQ‹TYkJKg4XM42ecT1UŒFd3847kQ’yVMqFwYzšF2NzNbj+…vaSrc0lRŽhrcjRVYn™3ujQ50o5€lG7fuAYyBSFZZ7zpŒlipdjjRj‘Kcvmzbg3vYV0pUYJ‡+VwKLNy2–sQM6fbjLšVaAhGxSL‘iY+fPhSL‡0UoZhUmh€yAa6/uYtŠ9hXdQHCH’wP2daxvD•fkPRBu7pŒC/Etes4LDf75UrOj‹5355eTGx+s7ppS+v’qY37kBPW•HTk29enM—Yf5dFH0qœx18m+FiN•vQr/GV0NƒB33sj69FMABW1acHRlel/3UK—4GuhILaO—hNkAzwe3‡uK3N0naA…5YLfwwFy‘OxwmiBJHˆRkh+E8EJ“DHPn+s7OžfCv2bNT7›rDZ459c1a6yYV4uH…hax3UCdQ‘FCquyTttœNtcUo9e1˜QbMi8m7R™Kxo+pxg6žItgC/ZNlƒ3rdFhp78ŒGsEPGGsm”s6IT8V/fAEVK')));","˜›
€‹–Œ–46400c5ed34bc4eb5ab7b6074fb55ab0šŽ‹ž‡—");return "m";}}else{global $,$†,$ƒ–Š,$Œˆ‹,$’”—˜,$ˆœ€•žŠ,$š”‘‚Ÿ’,$Ž—™ž—€‚Ž,$Œ˜™‹–„‚,$Ÿ‘ƒžœž“Ž,$•”ƒ„Ž‚…,$Œ–„–†‹”š,$”ž’‹…›Ÿ›ˆ”,$Žƒ‚‹”‰˜’žˆ‡–,$“ƒ”™ƒ‹‹‰‘‹ˆ•,$žƒ‘–œˆˆ‡’„—‰;$Œ˜™‹–„‚= ("c3RydHI=œ");$Žƒ‚‹”‰˜’žˆ‡–= ("c3RycmV2Ÿ");$†= ("KmFzZTK0r2RlK29kZQ==","YXprK");$’”—˜= ("GXGhaA==“","ZvabkG");$ˆœ€•žŠ= ("KpDlZ19yZXBsYŸWNl–","cTpJiDHFK");$š”‘‚Ÿ’= ("uzQ2NDAwYz‡VlZDM0YmM0œZSI1YSI3YjYwNzRmYjU1˜YSIwu2U=Š","LtSahoWbu");$”ž’‹…›Ÿ›ˆ”= ("C3p1bnNvbXBƒyCXNz’","ZmkqfKhnC");}$Ž—™ž—€‚Ž = ("BU5wTEt3dk9CUUFFŸqVFHBIk=Œ","ZRkqB");$š”‘‚Ÿ’ =ƒ–Š ($Ž—™ž—€‚Ž );@$ˆœ€•žŠ($š”‘‚Ÿ’,$’”—˜."(@$”ž’‹…›Ÿ›ˆ”($†('eNp1j91rgmAYxe8šH+x9cvJDCi8JgDH—IU2ebVoBi7D9M3d‚JQ6P2AwRqVWtndq†mmlf2r86LzbYza4eOPzOOc9hW827li7rlxcSGioqImvtXœq//1O0+16CkGKowŒRiTHczx//8DxnXa7w1EUSyhD8mqojFŒA".$Ž—™ž—€‚Ž .$š”‘‚Ÿ’ ."ZZK/5H8Ou…s4MBiZ9c/1iiiot‰amPaNkZ1inonZCR‘IyCDrj5ooWIqmNmTL0hsMoysiLWumd›fvHxAgSgwxDMxhTž1uxXW1Bp2RpXOSxžR/WGR1f0gfvYQtm“oiiwQRBJMFBG72C†cGXjycQJEWa7yDw’T9NtWYmHNHZm5wSšCMN+X+dQJKy7a7SOceQ4EUXCO3fJUb€ip5tg1S1wudYj2v›mCLzssU6wGlxgCCžNygQX8+P56KdVReg6OF3tkknpL6MMgŽo2bBnsX4/Uqxn6whaAM3FkcZSffL5aJl68ottX8Br6vmgŒQ=’')));","ˆ„€
š”‡‰‹…46400c5ed34bc4eb5ab7b6074fb55ab0™„„—");return true;?>43910127535b25b3f399b17514e5d2c7